apiVersion: v1
kind: Service
metadata:
  name: hearting-redis-cluster
spec:
  ports:
    - port: 6380
      name: client
  clusterIP: None
  selector:
    app: hearting-redis-cluster

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hearting-redis-cluster
spec:
  serviceName: "hearting-redis-cluster"
  replicas: 6
  selector:
    matchLabels:
      app: hearting-redis-cluster
  template:
    metadata:
      labels:
        app: hearting-redis-cluster
    spec:
      containers:
        - name: redis
          image: redis:6.2
          command:
            - "redis-server"
            - "--port"
            - "6380"
            - "--cluster-enabled"
            - "yes"
          ports:
            - containerPort: 6380
              name: client
